"""
Django settings for assignment2 project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import socket
# import environ
# import dj_database_url

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'restnearme/static/js', 'serviceworker.js')

# env = environ.Env()
# environ.Env.read_env()
# print(env('DATABASE_URL'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--zcqc&uhh_-d)2ujct7l4+-)*ww+&hfby&#8)mr#%8n+g8&^wz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['michelinrestaurants.site', '16.171.71.251', 'localhost', 'deployed_awm', '172.18.0.5']

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'whitenoise.runserver_nostatic',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pwa',
    'django.contrib.gis',
    'django.contrib.gis.db',
    'restnearme',
    'leaflet',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'assignment2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'assignment2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'giscourse',            
        'USER': 'docker',
        'PASSWORD': 'qwerty2023',
        'HOST': 'gis.c5cxvn3vbece.eu-north-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}

# DATABASES = {
#     'default': dj_database_url.parse(env('DATABASE_URL'), engine='django.contrib.gis.db.backends.postgis')
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Image)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# class docker_config:
#     POSTGIS_PORT = '5432'  
#     DEPLOY_SECURE = False
#     assignment2 = 'assignment2'

# if socket.gethostname() == "judes-Air":
#     DATABASES["default"]["HOST"] = "localhost"
#     DATABASES["default"]["PORT"] = 25432
#     DEPLOY_SECURE = False
# else:
#     DATABASES["default"]["HOST"] = "wmap_postgis"
#     DATABASES["default"]["PORT"] = 5432
#     DATABASES["default"]["USER"] = "docker"
#     DATABASES["default"]["PASSWORD"] = "docker"
#     DEPLOY_SECURE = True

#     # Set DEPLOY_SECURE to True only for LIVE deployment
# if DEPLOY_SECURE:
#     DEBUG = False
#     TEMPLATES[0]["OPTIONS"]["debug"] = False
#     # ALLOWED_HOSTS = ['.your-domain-name.xyz', 'localhost',]
#    # ALLOWED_HOSTS = ['michelinrestaurants.online', '16.16.126.78', 'localhost', 'deployed_awm', '172.19.0.5']
#     CSRF_COOKIE_SECURE = True
#     SESSION_COOKIE_SECURE = True
# else:
#     DEBUG = True
#     TEMPLATES[0]["OPTIONS"]["debug"] = True
#     ALLOWED_HOSTS = ['*', ]
#     CSRF_COOKIE_SECURE = False
#     SESSION_COOKIE_SECURE = False

# SECURE_HSTS_SECONDS = 31536000  # 1 year
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# SECURE_SSL_REDIRECT = True
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (53.0, -8.0),
    'DEFAULT_ZOOM': 6,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    'RESET_VIEW': False,
    'SCALE': None,
    'OPACITY': 0.5,
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


PWA_APP_NAME = 'Michelin Restaurants Near Me'
PWA_APP_DESCRIPTION = "RestaurantsNearMe PWA"
PWA_APP_THEME_COLOR = '#008080'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/login'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': 'static/image/restaurant-icon.png',
        'sizes': '160x160'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': 'static/image/restaurant-icon.png',
        'sizes': '160x160'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': 'static/image/restaurant-icon.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'

AWS_ACCESS_KEY_ID = 'AKIASABIDDC3YHNMJMCD '
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'giscourse'
AWS_S3_SIGNATURE_NAME = 's3v4',
AWS_S3_REGION_NAME = 'eu-north-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL =  None
AWS_S3_VERITY = True
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'