# Generated by Django 4.2.5 on 2023-12-06 23:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restnearme', '0002_alter_michelinrestaurants_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='michelinrestaurants',
            name='location',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
    ]
