# Generated by Django 4.2.5 on 2023-12-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restnearme', '0004_alter_michelinrestaurants_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='michelinrestaurants',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='michelinrestaurants',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
