# Generated by Django 4.2.5 on 2023-12-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restnearme', '0006_alter_michelinrestaurants_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='michelinrestaurants',
            name='city',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
    ]
