# Generated by Django 4.2.5 on 2023-12-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restnearme', '0007_alter_michelinrestaurants_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='michelinrestaurants',
            name='cuisine',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='michelinrestaurants',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='michelinrestaurants',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
